spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:15432/presentation
spring.datasource.username=yenniii
spring.datasource.password=VNpeDaFElE1lunf

logging.level.wisoft.kimbanana=debug